import { jsPDF } from 'jspdf';

const formatNumber = (value, maximumFractionDigits = 0) =>
  new Intl.NumberFormat('en-IN', { maximumFractionDigits }).format(value);

const formatCurrency = (value) => `INR ${formatNumber(value)}`;

const getReportRows = (analysis) => [
  ['Generated Date', new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  })],
  ['Location', analysis.location || 'Not specified'],
  ['Roof Area', `${formatNumber(analysis.roofArea)} m2`],
  ['Usable Area', `${formatNumber(analysis.usableArea, 1)} m2`],
  ['System Size', `${formatNumber(analysis.systemSize, 1)} kWp`],
  ['Estimated Panel Count', formatNumber(analysis.panels)],
  ['Estimated Monthly Energy', `${formatNumber(analysis.monthlyGeneration)} kWh`],
  ['Estimated Annual Energy', `${formatNumber(analysis.yearlyGeneration)} kWh`],
  ['Installation Cost', formatCurrency(analysis.installationCost)],
  ['Projected ROI', `${formatNumber(analysis.roi, 1)}%`],
  ['Payback Period', `${formatNumber(analysis.paybackPeriod, 1)} years`],
  ['Estimated Savings', `${formatCurrency(analysis.yearlySavings)} per year`],
  ['CO2 Reduction', `${formatNumber(analysis.co2Reduction)} kg per year`],
];

export const getLatestAnalysis = () => {
  try {
    return JSON.parse(localStorage.getItem('latestAnalysis'));
  } catch {
    return null;
  }
};

export const downloadAnalysisReport = (analysis) => {
  const document = new jsPDF();
  const pageWidth = document.internal.pageSize.getWidth();
  const margin = 20;
  const labelWidth = 72;
  let y = 28;

  document.setTextColor(15, 23, 42);
  document.setFont('helvetica', 'bold');
  document.setFontSize(18);
  document.text('SolarScope Rooftop Solar Analysis Report', margin, y);

  y += 8;
  document.setDrawColor(245, 158, 11);
  document.setLineWidth(1.2);
  document.line(margin, y, pageWidth - margin, y);

  y += 14;
  getReportRows(analysis).forEach(([label, value], index) => {
    if (index % 2 === 0) {
      document.setFillColor(248, 250, 252);
      document.rect(margin, y - 6, pageWidth - margin * 2, 11, 'F');
    }

    document.setFont('helvetica', 'bold');
    document.setFontSize(10);
    document.setTextColor(71, 85, 105);
    document.text(label, margin + 3, y);

    document.setFont('helvetica', 'normal');
    document.setTextColor(15, 23, 42);
    const valueLines = document.splitTextToSize(String(value), pageWidth - margin * 2 - labelWidth);
    document.text(valueLines, margin + labelWidth, y);
    y += Math.max(11, valueLines.length * 5.5);
  });

  document.setDrawColor(226, 232, 240);
  document.line(margin, 278, pageWidth - margin, 278);
  document.setFont('helvetica', 'normal');
  document.setFontSize(9);
  document.setTextColor(100, 116, 139);
  document.text('Generated by SolarScope', pageWidth / 2, 285, { align: 'center' });

  document.save(`SolarScope-Analysis-${new Date().toISOString().slice(0, 10)}.pdf`);
};
