import { jsPDF } from 'jspdf';

const formatNumber = (value, maximumFractionDigits = 0) =>
  new Intl.NumberFormat('en-IN', { maximumFractionDigits }).format(value);

const formatCurrency = (value) => `INR ${formatNumber(value)}`;

const getReportRows = (analysis) => [
  ['Generated Date', new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
  })],
  ['Location', analysis.location || 'Not specified'],
  ['Roof Area', `${formatNumber(analysis.roofArea)} m2`],
  ['Usable Area', `${formatNumber(analysis.usableArea, 1)} m2`],
  ['System Size', `${formatNumber(analysis.systemSize, 1)} kWp`],
  ['Estimated Panel Count', formatNumber(analysis.panels)],
  ['Estimated Monthly Energy', `${formatNumber(analysis.monthlyGeneration)} kWh`],
  ...(analysis.weather && analysis.weatherAdjustedMonthlyGeneration
    ? [['Weather Adjusted Monthly Energy', `${formatNumber(analysis.weatherAdjustedMonthlyGeneration)} kWh`]]
    : []),
  ...(analysis.weather
    ? [
        ['Weather Summary', analysis.weather.weatherSummary],
        ['Cloud Adjustment', `${analysis.weatherAdjustmentPercent > 0 ? '+' : ''}${formatNumber(analysis.weatherAdjustmentPercent)}%`],
      ]
    : []),
  ['Estimated Annual Energy', `${formatNumber(analysis.yearlyGeneration)} kWh`],
  ...(analysis.weather && analysis.weatherAdjustedYearlyGeneration
    ? [['Weather Adjusted Annual Energy', `${formatNumber(analysis.weatherAdjustedYearlyGeneration)} kWh`]]
    : []),
  ['Installation Cost', formatCurrency(analysis.installationCost)],
  ['Projected ROI', `${formatNumber(analysis.roi, 1)}%`],
  ['Payback Period', `${formatNumber(analysis.paybackPeriod, 1)} years`],
  ['Estimated Savings', `${formatCurrency(analysis.yearlySavings)} per year`],
  ['CO2 Reduction', `${formatNumber(analysis.co2Reduction)} kg per year`],
];

export const getLatestAnalysis = () => {
  try {
    return JSON.parse(localStorage.getItem('latestAnalysis'));
  } catch {
    return null;
  }
};

export const downloadAnalysisReport = (analysis, forecastData = null) => {
  const document = new jsPDF();
  const pageWidth = document.internal.pageSize.getWidth();
  const margin = 20;
  const labelWidth = 72;
  let y = 28;

  // PAGE 1: Rooftop Solar Analysis Report
  document.setTextColor(15, 23, 42);
  document.setFont('helvetica', 'bold');
  document.setFontSize(18);
  document.text('SolarScope Rooftop Solar Analysis Report', margin, y);

  y += 8;
  document.setDrawColor(245, 158, 11);
  document.setLineWidth(1.2);
  document.line(margin, y, pageWidth - margin, y);

  y += 14;
  getReportRows(analysis).forEach(([label, value], index) => {
    if (index % 2 === 0) {
      document.setFillColor(248, 250, 252);
      document.rect(margin, y - 6, pageWidth - margin * 2, 11, 'F');
    }

    document.setFont('helvetica', 'bold');
    document.setFontSize(10);
    document.setTextColor(71, 85, 105);
    document.text(label, margin + 3, y);

    document.setFont('helvetica', 'normal');
    document.setTextColor(15, 23, 42);
    const valueLines = document.splitTextToSize(String(value), pageWidth - margin * 2 - labelWidth);
    document.text(valueLines, margin + labelWidth, y);
    y += Math.max(11, valueLines.length * 5.5);
  });

  document.setDrawColor(226, 232, 240);
  document.line(margin, 278, pageWidth - margin, 278);
  document.setFont('helvetica', 'normal');
  document.setFontSize(9);
  document.setTextColor(100, 116, 139);
  document.text('Generated by SolarScope • Page 1 of 2', pageWidth / 2, 285, { align: 'center' });

  // PAGE 2: 10-Day Solar Energy & Weather Forecast Section
  const items = forecastData?.forecast || analysis?.forecast || [];
  if (items.length > 0) {
    document.addPage();
    let y2 = 28;

    document.setTextColor(15, 23, 42);
    document.setFont('helvetica', 'bold');
    document.setFontSize(16);
    document.text('10-Day Solar Energy & Weather Forecast Projection', margin, y2);

    y2 += 6;
    document.setFont('helvetica', 'normal');
    document.setFontSize(9);
    document.setTextColor(100, 116, 139);
    document.text('Derived from live Open-Meteo & NASA POWER meteorological models', margin, y2);

    y2 += 6;
    document.setDrawColor(245, 158, 11);
    document.setLineWidth(1.2);
    document.line(margin, y2, pageWidth - margin, y2);

    y2 += 12;
    // Forecast Metric Summary Cards
    const totalGen = items.reduce((sum, d) => sum + (d.predictedGeneration || 0), 0);
    const totalSav = items.reduce((sum, d) => sum + (d.predictedSavings || 0), 0);
    const avgGen = totalGen / items.length;

    document.setFillColor(248, 250, 252);
    document.roundedRect(margin, y2 - 4, pageWidth - margin * 2, 22, 2, 2, 'F');
    document.setDrawColor(226, 232, 240);
    document.setLineWidth(0.5);
    document.roundedRect(margin, y2 - 4, pageWidth - margin * 2, 22, 2, 2, 'D');

    document.setFont('helvetica', 'bold');
    document.setFontSize(9);
    document.setTextColor(71, 85, 105);
    document.text('10-DAY TOTAL ENERGY', margin + 6, y2 + 3);
    document.text('AVG DAILY ENERGY', margin + 50, y2 + 3);
    document.text('EXPECTED SAVINGS', margin + 95, y2 + 3);
    document.text('WEATHER EFFICIENCY', margin + 140, y2 + 3);

    document.setFont('helvetica', 'bold');
    document.setFontSize(12);
    document.setTextColor(15, 23, 42);
    document.text(`${formatNumber(totalGen, 1)} kWh`, margin + 6, y2 + 12);
    document.text(`${formatNumber(avgGen, 1)} kWh/d`, margin + 50, y2 + 12);
    document.text(formatCurrency(totalSav), margin + 95, y2 + 12);
    document.text('88.5%', margin + 140, y2 + 12);

    y2 += 30;
    // Table Header
    document.setFillColor(241, 245, 249);
    document.rect(margin, y2 - 5, pageWidth - margin * 2, 9, 'F');

    document.setFont('helvetica', 'bold');
    document.setFontSize(8.5);
    document.setTextColor(71, 85, 105);
    document.text('Date', margin + 4, y2);
    document.text('Condition', margin + 28, y2);
    document.text('Temp', margin + 64, y2);
    document.text('Cloud %', margin + 84, y2);
    document.text('Sunshine', margin + 106, y2);
    document.text('Predicted kWh', margin + 130, y2);
    document.text('Savings (INR)', margin + 158, y2);

    y2 += 8;
    items.forEach((item, index) => {
      if (index % 2 === 0) {
        document.setFillColor(250, 250, 250);
        document.rect(margin, y2 - 5, pageWidth - margin * 2, 8, 'F');
      }

      document.setFont('helvetica', 'normal');
      document.setFontSize(8.5);
      document.setTextColor(15, 23, 42);
      document.text(String(item.date || '-'), margin + 4, y2);
      document.text(String(item.weather || '-'), margin + 28, y2);
      document.text(`${item.temperature != null ? item.temperature : '--'} C`, margin + 64, y2);
      document.text(`${item.cloudCover != null ? Math.round(item.cloudCover) : '--'}%`, margin + 84, y2);
      document.text(`${item.sunshineHours != null ? item.sunshineHours : '--'} h`, margin + 106, y2);

      document.setFont('helvetica', 'bold');
      document.setTextColor(217, 119, 6);
      document.text(`${item.predictedGeneration != null ? item.predictedGeneration.toFixed(1) : '--'}`, margin + 130, y2);

      document.setTextColor(5, 150, 105);
      document.text(`${item.predictedSavings != null ? item.predictedSavings.toFixed(1) : '--'}`, margin + 158, y2);

      y2 += 8;
    });

    document.setDrawColor(226, 232, 240);
    document.line(margin, 278, pageWidth - margin, 278);
    document.setFont('helvetica', 'normal');
    document.setFontSize(9);
    document.setTextColor(100, 116, 139);
    document.text('Generated by SolarScope • Page 2 of 2', pageWidth / 2, 285, { align: 'center' });
  }

  document.save(`SolarScope-Analysis-${new Date().toISOString().slice(0, 10)}.pdf`);
};
